# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/x/git/eagle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/x/git/eagle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/eagle/CMakeFiles /home/x/git/eagle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/eagle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EAGLE

# Build rule for target.
EAGLE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EAGLE
.PHONY : EAGLE

# fast build rule for target.
EAGLE/fast:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/build
.PHONY : EAGLE/fast

common.o: common.c.o
.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i
.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s
.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/common.c.s
.PHONY : common.c.s

context.o: context.c.o
.PHONY : context.o

# target to build an object file
context.c.o:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/context.c.o
.PHONY : context.c.o

context.i: context.c.i
.PHONY : context.i

# target to preprocess a source file
context.c.i:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/context.c.i
.PHONY : context.c.i

context.s: context.c.s
.PHONY : context.s

# target to generate assembly for a file
context.c.s:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/context.c.s
.PHONY : context.c.s

eagle.o: eagle.c.o
.PHONY : eagle.o

# target to build an object file
eagle.c.o:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/eagle.c.o
.PHONY : eagle.c.o

eagle.i: eagle.c.i
.PHONY : eagle.i

# target to preprocess a source file
eagle.c.i:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/eagle.c.i
.PHONY : eagle.c.i

eagle.s: eagle.c.s
.PHONY : eagle.s

# target to generate assembly for a file
eagle.c.s:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/eagle.c.s
.PHONY : eagle.c.s

mem.o: mem.c.o
.PHONY : mem.o

# target to build an object file
mem.c.o:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/mem.c.o
.PHONY : mem.c.o

mem.i: mem.c.i
.PHONY : mem.i

# target to preprocess a source file
mem.c.i:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/mem.c.i
.PHONY : mem.c.i

mem.s: mem.c.s
.PHONY : mem.s

# target to generate assembly for a file
mem.c.s:
	$(MAKE) -f CMakeFiles/EAGLE.dir/build.make CMakeFiles/EAGLE.dir/mem.c.s
.PHONY : mem.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... EAGLE"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... eagle.o"
	@echo "... eagle.i"
	@echo "... eagle.s"
	@echo "... mem.o"
	@echo "... mem.i"
	@echo "... mem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

